spring.application.name=FinanceTracker

# Give your database a name and ensure it persists data to a local file so it doesn't wipe when you restart
spring.datasource.url=jdbc:mysql://localhost:3306/financedb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Enable the H2 Web Console so you can look at your tables in a browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Show SQL queries in the IntelliJ console (great for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true