spring.application.name=FinanceTracker

# Give your database a name and ensure it persists data to a local file so it doesn't wipe when you restart
spring.datasource.url=jdbc:h2:file:./data/financetrackerdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Enable the H2 Web Console so you can look at your tables in a browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Show SQL queries in the IntelliJ console (great for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Automatically update the database schema matching your Java classes
spring.jpa.hibernate.ddl-auto=update